sudo: required
language: generic
services:
    - docker 
    
before_install:
    - docker build -t harishindalkar/docker-react-travisci-test -f Dockerfile.dev .
    
script:
    # - docker run -e CI=true harishindalkar/docker-react-travisCI-test npm run test

    - travis_wait docker run harishindalkar/docker-react-travisci-test npm run test -- --coverage
